- cmd/hummingbird/main.go
- common/utils.go
This hasn't been needed since like 3 versions of go ago.
> remove UseMaxProcs

- bench/cbench.go
- cmd/hummingbird/main.go
- common/conf/policy.go
- common/conf/syncrealm.go
- containerserver/engine.go
- containerserver/engine_test.go
- containerserver/incoming_rep.go
- containerserver/incoming_rep_test.go
- containerserver/lib_test.go
- containerserver/replicator.go
- containerserver/replicator_test.go
- containerserver/schema.go
- containerserver/schema_test.go
- containerserver/server.go
- containerserver/server_test.go
- containerserver/sqlite_backend.go
- containerserver/sqlite_backend_test.go
- containerserver/update.go
- containerserver/update_test.go
Sorry, this is a huge massive patch.  I'm not sure what to do about that.
cbench on my SAIO with 10 concurrency, 5 containers, 50k objects:
SWIFT                               HUMMINGBIRD
OBJECT PUTs: 50000 @ 640.09/s       OBJECT PUTs: 50000 @ 2011.63/s
Failures: 0                         Failures: 0
Mean: 0.01562s (1403.0% RSD)        Mean: 0.00495s (867.7% RSD)
Median: 0.00561s                    Median: 0.00038s
85%: 0.00676s                       85%: 0.00045s
90%: 0.00710s                       90%: 0.00047s
95%: 0.00773s                       95%: 0.00067s
99%: 0.01071s                       99%: 0.16002s
CONTAINER GETs: 500 @ 2.49/s        CONTAINER GETs: 500 @ 6.26/s
Failures: 0                         Failures: 0
Mean: 3.99264s (538.9% RSD)         Mean: 1.59099s (31.3% RSD) …
> go: container server and replicator

- Makefile
- common/pickle/pickle.go
- common/pickle/pickle_test.go
- common/pickle/unpickle.go
If a tuple is used as a dict key, promote it to a PickleTuple struct
so it can act as a map key in go.
Support loading "array.array" objects to PickleArrays.  The way this
works is kind of messy because pickles are gross.
Also, fix for BINFLOAT endianness, since it was wrong.  Why are
integers stored little-endian and floats big-endian?  ¯\_(ツ)_/¯
fixes #8
> pickle support for builder files

- containerserver/engine.go
- containerserver/lib_test.go
- containerserver/server.go
- containerserver/sqlite_backend.go
- containerserver/sqlite_backend_test.go
- objectserver/main.go
Fix some new tests/functionality from swift from the last few months.
If-Match and If-None-Match needed to be a little more robust, and to
know about the X-Backend-Etag-Is-At header.
A Content-Range header needed to be added to 416 responses.
Container GET/HEAD needed a Last-Modified header, and that needs to
be updated on container POST.
> make current swift functional tests pass

- objectserver/repconn.go
- objectserver/replicator.go
- objectserver/replicator_test.go
- objectserver/repsrv.go
When syncing a file to multiple devices in a remote region, only
actually sync with one of them. For handoff replication, do an
in-sync check on the others so we can still remove objects that are
fully synced.  For non-handoff data, just send a ping to keep the
connection alive.
this is a port of: 
https://review.openstack.org/#/c/339296/
fixes #14
> go: more region-smart replication

- common/srv/server.go
range variable srv captured by func literal
https://golang.org/doc/faq#closures_and_goroutines
> Fix problem identified by go vet

- bench/main.go
- common/ring/memcachering.go
- common/ring/memcachering_test.go
- common/srv/router_test.go
- common/test/test.go
- common/utils.go
- common/utils_test.go
- proxyserver/main.go
- proxyserver/middleware/ratelimit.go
- proxyserver/middleware/ratelimit_test.go
If you set a [filter:ratelimit] section in the proxy-server.conf with
[filter:ratelimit]
account_db_max_writes_per_sec = 20
container_db_max_writes_per_sec = 100
it will limit the object writes (PUT/POST/DELETE) per container to 100/s
and writes directly to containers (PUTs to /v/a/c) to 10/s
fixes #43
> Proxy layer ratelimiting

- accountserver/server.go
- containerserver/server.go
order of operations is hard.
I messed up an if-check that causes basically all headers to be saved
in account metadata.  I made the filter checks for both account and
containers a little more robust.
> fix metadata saving

- proxyserver/main.go
- proxyserver/middleware/context.go
- proxyserver/middleware/formpost.go
- proxyserver/middleware/formpost_test.go
Implements formpost middleware, which allows objects to be uploaded
by browser form post.  The POST requests are authenticated by a
hidden "signature" field in the form.
Unfortunately there are no functional tests for this.
fixes #47
> formpost middleware

- client/directclient.go
- client/directclient_test.go
- proxyserver/accounthandlers.go
- proxyserver/containerhandlers.go
- proxyserver/main.go
- proxyserver/middleware/context.go
- proxyserver/middleware/formpost_test.go
- proxyserver/middleware/tempurl_test.go
- proxyserver/objhandlers.go
This is work towards #80 
It allows creating containers with policies other than the default, and to work with objects in such containers.
Remaining work deals with returning the appropriate informative headers, to included account-level metrics.
> Initial work for end user policy support

- proxyserver/constraints.go
- proxyserver/constraints_test.go
Golang's http.Request makes it a little tough to tell if the content length header is missing.
> Content length checking

- objectserver/swiftobjeng.go
- objectserver/swiftobjeng_test.go
Just because gholt mentioned how silly the name was.
> rename SwiftObjectFactory to SwiftEngine

- proxyserver/middleware/formpost.go
It's buffering the full form POST before processing, which is bad.
This was something I accidentally left in while debugging.
> stop buffering formpost POST body

- common/pickle/pickle.go
- common/pickle/unmarshal.go
- common/pickle/unmarshal_test.go
Treat any struct with two fields with the first one is named
"ArrayType" as an array for pickle purposes.  I could tighten up that
interface a bit, but it doesn't seem likely to get triggered
accidentally.
> handle custom array types in pickles

- client/directclient.go
- proxyserver/accounthandlers.go
- proxyserver/containerhandlers.go
Container GETs treat an empty path query param differently than path
not being there.  Ignoring the wisdom of this for the moment, make it
work.
> pass empty path param on container GET

- proxyserver/objhandlers.go
Strip any charset from automatic content types.
Specifically, it was returning ".txt" -> "text/plain; charset=utf-8"
> remove charsets from auto content-type

- client/client.go
- client/directclient.go
- common/conf/conf.go
- common/conf/conf_test.go
- common/utils.go
- common/utils_test.go
- proxyserver/accounthandlers.go
- proxyserver/containerhandlers.go
- proxyserver/main.go
- proxyserver/middleware/acl.go
- proxyserver/middleware/acl_test.go
- proxyserver/middleware/authtoken.go
- proxyserver/middleware/authtoken_test.go
- proxyserver/middleware/context.go
- proxyserver/middleware/copy.go
- proxyserver/middleware/copy_test.go
- proxyserver/middleware/formpost.go
- proxyserver/middleware/keystoneauth.go
- proxyserver/middleware/largeobject.go
- proxyserver/middleware/tempurl.go
- proxyserver/objhandlers.go
In order to test this, I have created a dockerized keystone
https://github.com/nadeemsyed/dockerized-keystone
In order to enable keystoneauth middleware, you would need to add following entry in proxy.conf
tempauth_enabled = false
Some tests are still failing due missing OPTIONS call support in proxy and some issues with other middleware. Also no support for Account ACLs till now.
Hopefully we will fix them one by one.
If we want, may be we can update travis to use keystone for its tests.
> Implement couple of keystoneauth middleware along with acls.

- common/srv/server.go
Swift uses 'text/html; charset=UTF-8' as default content type
and some functional tests checks for that.
So be it.
> Change the default Content-Type to match Swift.

- bench/main.go
- client/client.go
- client/directclient.go
- client/userclient.go
- proxyserver/accounthandlers.go
- proxyserver/containerhandlers.go
- proxyserver/middleware/context.go
- proxyserver/objhandlers.go
The client code was getting a little silly with some functions returning
body, headers, and status and I needed to also return explantory error
bodies for things like "Storage Policy %q is deprecated". Anyway, after
trying different approaches at the problem, I settled on just returning
*http.Response instances. It's not that much harder to check for errors
this way, and is much easier to get at all the information you might
need.
Close #79
> Refactor client code to just return *http.Responses

- .travis.yml
- accountserver/replicator.go
- accountserver/server.go
- cmd/hummingbird/main.go
- common/ring/ring.go
- common/ring/ring_test.go
- common/srv/server.go
- common/utils.go
- containerserver/replicator.go
- containerserver/server.go
- objectserver/auditor.go
- objectserver/main.go
- objectserver/replicator.go
- proxyserver/main.go
Use -l [stdout] -e [stderr] to set log destinations, get rid of -v.
Wire up "hummingbird start" to set them to /var/log/hummingbird/*.
Get rid of -d, since apparently nobody does that anymore.
Remark that "hummingbird start" shouldn't be used for production.
Various little cleanups, since I was in the neighborhood.
> some logging/cmd stuff

- objectserver/repsrv.go
There wasn't a route that could be used to access it.
> make http pprof accessible in replicator

- README.md
Mainly the directory level is 1 less against the one we had when nested under Swift. Also adds Go 1.8 as requirement and other things I ran into when trying to follow the steps.
> Update README for the troubling

- proxyserver/middleware/authtoken.go
- proxyserver/middleware/context.go
- proxyserver/middleware/copy.go
- proxyserver/middleware/formpost.go
- proxyserver/middleware/keystoneauth.go
- proxyserver/middleware/largeobject.go
- proxyserver/middleware/multirange.go
- proxyserver/middleware/staticweb.go
- proxyserver/middleware/tempauth.go
- proxyserver/middleware/tempurl.go
* Dropped AuthorizeOverride. It just served for confusion and can be
readded if we ever truly understand and can explain why we need it.
* Refactored Subrequest into newSubrequest and serveHTTPSubrequest. This
means you create the http.Request object with all the proper stuff
copied over and then can tweak it before processing/serving it.
* Refactored Keystone middleware to only set the Authorize func for its
configured reseller prefixes. Swift supports the notion of fallback
auth for unconfigured reseller prefixes and that's why it needed
AuthorizeOverride (I think) etc. It was kind of a mess we don't really
need to emulate.
* New subrequestCopy infrastructure gives a hook for any middleware
to copy over request-level data for a subrequest. Keystone loves it
some headers and will reject …
> Refactor of Subrequest and minor auth changes

- proxyserver/middleware/staticweb.go
- proxyserver/middleware/staticweb_test.go
This patch helps in passing test_rbac_with_service_prefix functional test.
Now all the functional tests in test_access_control pass with Keystone.
> Update staticweb to work with X-Service-Token

- client/client.go
- client/directclient.go
- proxyserver/containerhandlers.go
- proxyserver/middleware/context.go
- proxyserver/middleware/cors.go
- proxyserver/middleware/formpost.go
- proxyserver/middleware/keystoneauth.go
- proxyserver/middleware/staticweb.go
- proxyserver/middleware/tempurl.go
- proxyserver/objhandlers.go
These now return info, err instead of relying on the caller to remember
that they're supposed to check for nils. Of course, they can still
forget to check for err != nil, but that's more of a idiomatic Go thing
so hopefully easier to remember.
> HUM-153 Refactor GetAccountInfo GetContainerInfo

- proxyserver/accounthandlers.go
- proxyserver/containerhandlers.go
- proxyserver/main.go
- proxyserver/middleware/context.go
- proxyserver/middleware/keystoneauth.go
Now in proxy-server.conf we will need to have account
auto creation set to true. Default is false:
[app:proxy-server]
account_autocreate = true
Moved the auto account creation logic from GetAccountInfo
to proxy handlers. Now we auto create account on Account GET/HEAD/POST &
Container PUT request.
Also fixed a typo in keystoneauth setProjectDomainID.
Now more functional tests should pass. Yay!
Fixes #52
> Auto create account

- client/directclient.go
- client/directclient_test.go
Handle setting update headers when the number of container servers
doesn't equal the number of object servers.
Ditto number of account servers and container servers.
Ninja bump post quorum timeout do to the occasional continued goof.
> HUM-186 handle mismatched replica counts

- client/directclient.go
I'm not 100% sure the err != nil && response != nil case can really
happen, but there are a few rumblings online about it.  The firstResponse case with all the odd status checks was the major culprit.
> Close all the things.

- proxyserver/middleware/copy.go
No need to log every time a client drops their connection.
> HUM-220 Suppress closed pipe errors

- client/userclient.go
User client can't retry request on its own because the request body may
have been closed and the original caller would need to reset it, if
possible.
> HUM-224 User client can't retry request on its own

- objectserver/backend.go
- objectserver/replicator.go
- objectserver/replicator_test.go
- objectserver/repsrv.go
- objectserver/update.go
- objectserver/updater.go
- objectserver/updater_test.go
- probe/base.go
I mean, I've tried to make it not too horrible.
The workers are sort of converging on a shared interface.
Also some replicator cleanup.
Remove ms_per_part setting.  Permanently set that to 10 ms.
Make replication_limit only settable per-device, not globally.
People have already screwed around with those two settings without
understanding them.
Get stats out of replication device struct and into the replicator.
Some other cleanup - un-exporting things if they don't need it.
> updater crammed into replicator

- proxyserver/middleware/authtoken.go
- proxyserver/middleware/authtoken_test.go
- proxyserver/middleware/keystoneauth.go
Use memcache GetStructured instead of Get in authtoken.
Now Keystone test is quite fast.
> HUM-246 Fix a bug in authtoken middleware

- common/pickle/pickle.go
- common/pickle/pickle_test.go
- common/pickle/unpickle.go
Add support for reading and writing binary "H" and "B" pickle arrays,
to improve the performance of ring builders.
This is a little treacherous because they're not technically portable
or well defined in python.  But we need to speed things up and these
two array types should be fine, mostly, usually.
> binary pickle arrays

- accountserver/server.go
- containerserver/server.go
- middleware/dbgheader.go
- objectserver/main.go
- proxyserver/main.go
- proxyserver/middleware/context.go
Support for a new config option in proxy, object, container and
account servers,
[debug]
debug_x_source_code = true
This causes the server to add an X-Source-Code header to the
response, containing the stack trace at the point where
WriteHeader was called.  This should be useful in tracking down
which code generates an unexpected response.
> HUM-288 debugging stack traces in headers

- client/directclient.go
- containerserver/server.go
- objectserver/main.go
Bump MaxIdleConnsPerHost in some clients that get a lot of use.
Make sure MaxIdleConns is 0 everywhere.
Make the idle connection timeout more aggressive (5 seconds).
This should make us put fewer proxy->object and object->container
connections into time_wait when doing a lot of concurrency, but
idle conns will also be reaped more quickly once they're unused.
> increase more idle conn limits

- client/directclient.go
- proxyserver/containerhandlers_test.go
- proxyserver/middleware/formpost_test.go
- proxyserver/middleware/staticweb_test.go
- proxyserver/middleware/tempurl_test.go
- proxyserver/middleware/versioned_writes_test.go
The proxy client never re-uses container info.  There's a place to
cache it, and it's checked, but it's never set.  This means that the
container info can be fetched from memcache 4 or 5 times per request.
I also took the opportunity to rework things so we don't create
new proxy object clients for every operation.  They are created once,
when the proxy client is created.
> proxy client and container info cache

- objectserver/ec/engine.go
- objectserver/main.go
- objectserver/objengine.go
Policies might need to handle requests aside from the pre-allowed ones
(e.g. EC chunk GETs).  This lets obj engines optionally register http
handlers and creates some dummy ones for EC.
> HUM-264: allow policies to register web handlers

- objectserver/ec/engine.go
- objectserver/ec/obj.go
- objectserver/ec/utils.go
Fix a couple of show stopper bugs in the initial EC code.
Ephemeral ports are being exhausted by runaway time-waits, hopefully
mitigated by increasing the max idle conns setting (like we've had to
do everywhere).  Also fixing one spot where I failed to discard a
response body, so the connection couldn't be reused.
A nil crash cauesd by ecSplit modifying the slice it was given as an
argument and the caller not expecting that.
> HUM-390: ec ephemeral port usage and nil crash

- accountserver/sqlite_backend.go
- containerserver/sqlite_backend.go
That code looked racy and it's kind of the only place we do anything
weird with sqlite, so lock down the whole hashdir during db creation
to see if serializing that fixes it.
> HUM-412: lock hashdir during db creation

- containerserver/engine.go
- containerserver/lib_test.go
- containerserver/replicator.go
- containerserver/sqlite_backend.go
- containerserver/sqlite_backend_test.go
Container reporting now remembers the last report it made so as to not
repeat the same report over and over.
> HUM-411 Container Reporting

- common/srv/server.go
When debug_x_source_code is enabled, the replicator panics all over the place. Change customWriter to a http hijacker.
> HUM-497 customWriter should be a hijacker for replicators

- cmd/hummingbird/main.go
- tools/dispersion.go
- tools/drivewatch.go
- tools/drivewatch_test.go
- tools/reconcli.go
only update ring if there hasn't been one in ring_update_frequency_sec and
there has been a previous run in last run_frequency_sec*2.  by default thats 2
hours
also change config do_not_rebalance (default f) to update_ring (default t).
before it would zero devices but maybe not rebalance. now it is change ring at
all. this should make things simpler.
need to add a new call to update status report on overdue, unmounted drives.
people could use that to update ring manually if they wanted.
> HUM-483 : make andrewd not change ring for a bit

- objectserver/ec/engine.go
- objectserver/ec/indexdb.go
Have the object server look for any local version when instantiating
existing ec objects.  This should fix several places that we get
unexpected 404s after stabilization.
> HUM-496: fix 404 on missing shard 0

- common/ring/ring.go
- common/test/test.go
- middleware/recon.go
- middleware/recon_test.go
- objectserver/priorityrep_test.go
- tools/dispersion_test.go
- tools/main.go
- tools/quarantinerepairman.go
- tools/reconcli.go
- tools/reconcli_test.go
This adds a background job to andrewd that will scan the whole cluster
for quarantined items and repair them. For items that it has the name
for, it can repair just that item by pulling from a node that has a
copy. For items that it just knows the hash of, it can queue up a
replication pass for that partition.
There are some ancillary changes in here too:
The recon quarantine detail responses had to start including the device
data as well.
I needed to add PartitionForHash to the ring since sometimes the only
thing we know about a quarantined item is what its ring hash was, so the
best we can do is ask for a full replication cycle for the corresponding
partition.
I added a getDB to AutoAdmin. I'd like to move all the DB instantiation
stuff there, such as out of drivewatch, but I'll leave …
> HUM-518 Andrewd Quarantine Repairman

- cmd/hummingbird/main.go
- docs/replication-tools.md
- objectserver/priorityrep.go
- objectserver/priorityrep_test.go
- objectserver/replicator.go
- objectserver/replicator_test.go
- tools/dispersion.go
- tools/drivewatch_test.go
this cmd isn't really used and this allows changes priorityrepl jobs
to just have a single todevice- which simplifies handling them.
the only things to use multiple ToDevices is rescuepartitions
and RescueLonelyPartitions. first removed, second refactored
> HUM-577 : get rid of rescuepartition command

- objectserver/indexdb/utils.go
While doing GET call for EC objects, we might get better performance if we use
ReconstructData instead of Reconstruct.
https://github.com/klauspost/reedsolomon#performance
Also while doing Reconstruct/ReconstructData we could shave off one allocation
if we use zero-length buffer with adequate capacity instead of passing nil.
> HUM-575 Couple of small EC GET optimization

- tools/dispersionscancontainers.go
- tools/dispersionscanobjects.go
Can't suppress 100% of it since some checks are done via a proxy-client,
such as the populations and the HEADs for the -init markers and GETs for
container listings. But it suppresses most of the scans.
> HUM-613 Suppress dispersion request logging

- objectserver/indexdb/ecengine.go
when the object got stabilized the ETag got sent over as a Meta-Etag
header. I'm special casing it to be saved as ETag in db. this is
basically in line with what is done on whole objects
> HUM-567 : cant overwrite obj in EC

- objectserver/indexdb/ecengine.go
- objectserver/indexdb/ecobj.go
- objectserver/indexdb/ecobj_test.go
Serve EC range requests.
We have to grab block-aligned chunks from the fragments, then discard
any bytes we don't need.  I used a proxy Writer to do the discarding,
to keep ecGlue "simple".
> HUM-614 EC range requests

- common/expects.go
- common/expects_test.go
- objectserver/indexdb/ecobj.go
Consolidate expector Cancel and Close, just because we don't need
both.
Then when it gets a response to a request, go ahead and close the Body
if the expector has been closed/canceled, so it's not left dangling.
> HUM-638 make sure ec stabilizer closes bodies

- common/ring/builder.go
- tools/ring.go
Removed devices now also stay in the ring with a weight of -1
so that external tools can see that they have been removed.
If the device needs to go back into the ring, it can be done by
changing its weight.
> HUM-607 Removing device from ring sets weight -1

- accountserver/sqlite_backend.go
- containerserver/sqlite_backend.go
- objectserver/auditor.go
- objectserver/auditor_test.go
Pretty much this just cleans up the logs a bit. The error wasn't getting propagated all the way back to the client before, it was just a bit of log spam and didn't seem "correct" to me.
> HUM-653 Autocreate success when already created; typos

- objectserver/indexdb/ecengine.go
- objectserver/indexdb/indexdb.go
- objectserver/indexdb/indexdb_test.go
- objectserver/indexdb/indexdbobjeng.go
Call Preallocate() on shards.
Preallocating space for files reduces fragmentation and lets us
reject requests early when the drive is full.
> HUM-666 preallocate temp files in hec

- objectserver/ecengine.go
- objectserver/main.go
- tools/dispersionpopulateobjects.go
- tools/dispersionscancontainers.go
- tools/dispersionscanobjects.go
When there's a HEC policy, the shards of the dispersion objects will now
be scanned for and replication jobs queued for missing shards.
Before, it would just query each of the many devices from ring.GetNodes
for the full object, and every single one would respond successfully if
there had been at least data:shards in place. Lots of extra work and
useless in the end.
One side effect on this new change is that before the dispersion objects
get stabilized it will seem to the scanner that all the shards are
missing (since they essentially are) and it will queue up a bunch of
wasted effort replication jobs. In practice this shouldn't be a big deal
as it will only happen right after a dispersion populate and before
stabilization, and the cluster or policy should be brand new with near
zero data …
> HUM-451 Dispersion scan support for HEC

- client/directclient.go
- client/nodeiter.go
- client/nodeiter_test.go
- proxyserver/main.go
- tools/main.go
Which is a pretty grandiose name for using slightly different node
sorting strategies.  Implemented (mostly) as described here:
https://docs.openstack.org/swift/ocata/overview_global_cluster.html
This lets you set read and write affinity.  Nobody should probably
ever use write affinity, but it is included for feature parity and
because it's not that complicated.
I didn't implement sorting_method, it just uses read affinity if it's
set.
> HUM-676 Global Clusters

- common/ring/ring.go
- tools/ringmonitor.go
- tools/ringscan.go
RingMD5s are no longer cached by default; the code that uses RingMD5s
can cache if it wants to. This will ensure we can somewhat reason about
when the data underlying the RingMD5 can change. Before the ring monitor
and the ring scanner could affect one another, mid-pass.
I also improved the ring scan to break out of a slow scan when a fast
scan is requested, mid-pass.
I improved the ring monitor's auto-rebalancer to take into account
zero-weight devices. It should now continue to rebalance when
zero-weight devices still have assignements, even if the last rebalance
changed a very tiny number of assignments. This required a new
AssignmentCount method on the RingMD5s.
I also fixed a bug in the logic from before where it would not queue up
replication jobs for auto-rebalance changes.
> HUM-725 Rework RingMD5 a bit

- tools/dispersionpopulatecontainers.go
- tools/dispersionpopulateobjects.go
- tools/dispersionscancontainers.go
- tools/dispersionscanobjects.go
- tools/quarantinehistory.go
- tools/quarantinerepair.go
- tools/replication.go
- tools/ringmonitor.go
- tools/ringscan.go
- tools/unmountedmonitor.go
Now when a device is cleared from a ring, or attempted to be cleared
from a ring, any more attempts to clear it from that ring will be
ignored for a while (4 hours by default).
This is needed because the servers report all unmounted devices for
forever and forever trying to remove them from the builders is more
wasteful than I thought. Loading those builders up just to check if the
device is in the ring takes a lot more time than I thought, especially
with 2**22 rings.
Anyway, we can't permanently ignore them after ensuring they're cleared
because someone could add them back in outside of Andrewd. So... ignore
durations!
> HUM-722 Andrewd unmounted monitor optimization

- middleware/recon.go
- objectserver/auditor.go
- objectserver/auditor_test.go
- objectserver/repobjeng.go
this will also move rep index.db's and data into
rep and rep.db like how hec works
also changed name of quarantined meta files to idbmeta
added auditorType to log line because sometimes they
run over each other on AIOs
> HUM-806 : refactor auditor to take rep objects

- common/tracing/util.go
- containerserver/update.go
- objectserver/update.go
- proxyserver/middleware/authtoken.go
authtoken's preValidate function creates a separate goroutine to
validate/prepopulate token in cache before expiry.
Recently we added context.Context to this call, which uses parent
request's context to propagate tracing info. However side-effect
of using parent request's context is that when parent request
ends it send cancel signal to all of its derived context. Hence preValidate
goroutine call was always failing with 'context canceled' error.
In order to fix this now we create a new Context and extract the tracing span from original
request's context. We then inject the extracted span into new Context and use this context.
This PR also fix similar problem  with containerserver's accountUpdate & objectserver's
containerUpdates functions.
> HUM-866 Fix 'context canceled' error with authToken.go preValidate call

- common/expects.go
- common/expects_test.go
- objectserver/auditor.go
- objectserver/auditor_test.go
- objectserver/ecengine.go
- objectserver/ecobj.go
- objectserver/ecobj_test.go
- objectserver/ecutils.go
- objectserver/indexdb.go
- objectserver/indexdb_test.go
- objectserver/repobj.go
- objectserver/repobjeng.go
and change everybody to use srv.LowLevelLogger
StablePut now returns a 409 if the file is already there
Expector Successes refactor
> HUM-848 : audit object before tempfile accepts it as already there

- objectserver/nurserystabilizer.go
- objectserver/objengine.go
- objectserver/replicator.go
- objectserver/replicator_test.go
- objectserver/repsrv.go
- objectserver/swiftobjeng.go
- tools/reconcli.go
note: these stats are cleared at end of each run (10s)
to see them hit:
curl http://127.0.0.1:8010/progress/object-nursery | python -m json.tool
> HUM-836 : report stats for nursery stabilizer

- objectserver/nurserystabilizer.go
- objectserver/replicator.go
- objectserver/repsrv.go
Easiest way to mess with this is to put a `time.Sleep(15*time.Second)`  inside the `for := range c {` loop in objectserver/nurserystabilizer.go's `Scan` function and then do a quick `nectar bench-put container` or similar to get some objects in a hec or rep policy.
> HUM-867 Metrics for stabilization

- client/objclient.go
- client/proxyclient.go
As we are using goroutine in quorumResponse & firstResponse and bailing out earlier,
passing the proxy context as it is down the stack causes "context cancelled" error.
This patch extract the tracing span from the proxy request's Context and
inject it into a new Context which is passed down the stack.
> HUM-891 Fix context canceled error msg in proxy.

- accountserver/engine.go
- accountserver/engine_test.go
- accountserver/incoming_rep.go
- accountserver/incoming_rep_test.go
- accountserver/replicator.go
- accountserver/replicator_test.go
- accountserver/sqlite_backend.go
- accountserver/sqlite_backend_test.go
- common/fs/main.go
Basically, make sure it grabs a flock on the hash dir *any* time it
deals with the database as a file on the filesystem.
Also, make sure that when it renames database files, any journals
move with database and old journals get removed.
When pulling a cached connection out of the pool, make sure the
underlying inode hasn't changed.
Get rid of the rsync_then_merge replication strategy, since it's not
super useful for accounts and can cause problems.
> HUM-897 close some race conditions in account

- objectserver/ecobj.go
- objectserver/repobj.go
To be honest, I'm not 100% sure why I'm doing this; the JIRA had little explanation. I'm guessing it is so that the timestamp is in the logs.
> HUM-647 Add X-Timestamp to Replicate functions

- middleware/recon_test.go
If you're running go test locally in the middleware dir on a fairly idle
box, this test would often fail since the system load would often be
zero.
> HUM-522 Just require load to be >= 0

- proxyserver/middleware/s3api.go
- proxyserver/middleware/s3auth.go
Support basic multi-part uploads.  Handle the following request types:
POST /container/object?uploads                   // begin upload
PUT /container/object?partNumber=X&uploadId=XXXX // put part
POST /container/object?uploadId=XXXX             // complete upload
DELETE /container/object?uploadId=XXXX           // abort upload
GET /container/object?uploadId=XXXX              // list parts
GET /container/?uploads                          // list uploads
The object segments are stored in a side-container named
"[container name]+segments", and the object is saved as a static
large object pointing to those segments.
> HUM-864 s3api multipart uploads

- objectserver/indexdb.go
There does not seem to be a need for the extra lookup. It just offers the ability to return a 404 or a 409 and the far end doesn't really care and Commit does the same check albeit without returning the exact status codes.
> HUM-655 Simplify StablePost

- proxyserver/middleware/s3api.go
- proxyserver/middleware/s3api_test.go
Add a couple headers that aws sends that are just duplicates of the
request id.
Add a helper for the proper date format. Not all date occurences
are fixed yet.
> Some s3api nitpicks.

- .swift_func_excludes
- proxyserver/middleware/s3api.go
This fixes the swift info typo that was stopping func tests. However,
since there's a lot of broken stuff here, the actual s3api tests are
excluded. You can run them outside of the hbswifttests script.
> HUM-855 Last bit of misc to run swift func tests
