troubling/hummingbird

- common/test/test.go
- containerserver/incoming_rep_test.go
- containerserver/lib_test.go
- containerserver/replicator_test.go
- containerserver/server_test.go
- containerserver/update_test.go
- objectserver/main_test.go
- objectserver/replicator.go
- objectserver/replicator_test.go
- probe/base.go
DO NOT MERGE YET!  Just seeking input to see if I'm on the right track
fixes #6
> objectserver tests run without swift configs

- Makefile
- cmd/hummingbird/main.go
- common/srv/router.go
- common/version.go
- containerserver/server.go
- middleware/options.go
- middleware/recon.go
- objectserver/main.go
Also add support for OPTIONS call in object & container server.
Fixes #28
> Add time & driveaudit options in hummingbird recon middleware

- accountserver/engine.go
- accountserver/engine_test.go
- accountserver/incoming_rep.go
- accountserver/incoming_rep_test.go
- accountserver/replicator.go
- accountserver/replicator_test.go
- accountserver/schema.go
- accountserver/server.go
- accountserver/server_test.go
- accountserver/sqlite_backend.go
- accountserver/sqlite_backend_test.go
- cmd/hummingbird/main.go
This is basically a fork of the container server.
I'd like to try and figure out some places we can consolidate them
later, but this will do for now.
fixes #30
> account server

- containerserver/engine.go
- containerserver/engine_test.go
- containerserver/lib_test.go
- containerserver/server.go
- containerserver/server_test.go
> Close container db on policy conflict

- .travis.yml
It's not very pretty.  But it runs tests.  So.
fixes #15
> working travis ci config

- .travis.yml
- Makefile
- bench/cbench.go
- common/test/test.go
- common/utils_test.go
- containerserver/incoming_rep_test.go
- containerserver/replicator_test.go
- containerserver/server_test.go
- containerserver/sqlite_backend_test.go
- proxyserver/middleware/context.go
- proxyserver/middleware/ratelimit.go
Also added checks in .travis.yml & Makefile to catch this going forward.
> Run gofmt again with simplify option.

- client/directclient.go
firstResponse will currently kill a request's cancel channel before
returning it, which makes the GET die at some point later, cutting
downloads short.  This should fix that.  It's probably not the
prettiest solution, but it'll work for now.
fixes #5
> fix firstResponse channel closing

- containerserver/replicator.go
Missing a Close() on a database.
> fix container replicator leak

- cmd/hummingbird/main.go
while starting container & account replicator
> Fix typo in startup script

- accountserver/sqlite_backend_test.go
- bench/main.go
- client/client.go
- client/directclient.go
- client/userclient.go
- proxyserver/accounthandlers.go
- proxyserver/objhandlers.go
> Return Etag on PUT. Fix simple container list ordering.

- client/directclient.go
Full fix of this area (abort on any error) will have to wait until
later.
> Quick fix for MultiWriter code assumption of 3 replicas

- proxyserver/constraints.go
- proxyserver/constraints_test.go
- proxyserver/containerhandlers.go
(cherry picked from commit 253eb63d8a1cc50889835360a63a1efdcfbd5aae)
> Check container name length

- .travis.yml
Not gating for now, just run them so we can see the results.
> add all-hb func tests to travis

- .travis.yml
by using https://github.com/haya14busa/goverage.
Update travis to use this new coverage.out
> Generate single cover output for all hummingbird pkgs

- proxyserver/middleware/copy.go
- proxyserver/middleware/copy_test.go
> Destination

- accountserver/sqlite_backend_test.go
- proxyserver/middleware/copy.go
- proxyserver/middleware/copy_test.go
Also it doesn't return all the headers.
> PostAsCopy returns 202 instead of 201.

- common/srv/server.go
- proxyserver/middleware/catcherror.go
- proxyserver/middleware/context.go
- proxyserver/middleware/copy.go
- proxyserver/middleware/copy_test.go
- proxyserver/middleware/formpost.go
- proxyserver/middleware/formpost_test.go
Unified context subrequests that hit entire pipeline.
Some cleanups.
> context subrequests

- common/utils.go
- common/utils_test.go
- containerserver/server.go
- objectserver/main.go
- proxyserver/accounthandlers.go
- proxyserver/containerhandlers.go
- proxyserver/middleware/context.go
- proxyserver/middleware/formpost.go
- proxyserver/middleware/tempurl.go
- proxyserver/middleware/tempurl_test.go
- proxyserver/objhandlers.go
Fix it so X-Timestamp is chosen in one place for incoming requests.
Start some time utility function cleanup/unification.
> x-timestamps and some cleanup

- common/conf/policy.go
- common/conf/policy_test.go
- proxyserver/constraints.go
- proxyserver/main.go
> Expose details regarding policies & constraints in swift info

- proxyserver/middleware/tempauth.go
> have tempauth set RemoteUser

- accountserver/server.go
- containerserver/server.go
It seems like we added the http pprof route out of order.
> Fix http pprof in Account & Container.

- objectserver/auditor_test.go
- objectserver/main_test.go
- probe/base.go
Not sure if this extra argument approach is the best, but seems like the least worst idea.
> Check for an error from NewAuditor and GetServer

- client/directclient.go
- objectserver/main.go
- objectserver/main_test.go
- objectserver/objengine.go
- objectserver/swiftobjeng.go
- objectserver/swiftobjeng_test.go
- objectserver/update.go
- objectserver/update_test.go
- proxyserver/main.go
- proxyserver/middleware/copy.go
- proxyserver/middleware/copy_test.go
- proxyserver/objhandlers.go
This is post-as-copy if the Content-Type is set, otherwise it will do a
fast post. We'll discuss later if we want to implement the complexity of
Swift's Content-Type timestamping.
Closes #11
> Sorta-Fast-Post implementation

- proxyserver/middleware/copy.go
- proxyserver/middleware/copy_test.go
- proxyserver/middleware/largeobject.go
Just a general PR for things I'm finding while trying to clear up failing functional tests.
> Working on functional tests

- proxyserver/constraints.go
- proxyserver/constraints_test.go
Make both testNoContentLengthForPut and testChunkedPut pass at the same time.
> HUM-171 fix content-length/chunked requirement

- proxyserver/middleware/keystoneauth.go
> Set X-Account-Project-Domain-Id

- common/test/test.go
- proxyserver/middleware/acl.go
- proxyserver/middleware/context.go
- proxyserver/middleware/keystoneauth.go
- proxyserver/middleware/tempauth.go
- proxyserver/middleware/tempauth_test.go
> HUM-169 : refactor tempauth

- cmd/hummingbird/main.go
- common/pickle/pickle.go
- common/ring/builder.go
- common/ring/ring.go
Enough is there to run the remakerings script for an all in one.
Still very experimental at this stage.
Example usage:
`./hummingbird ring-builder create ./object.builder 10 3 1`
`./hummingbird ring-builder add ./object.builder r1z1-127.0.0.1:6010R127.0.0.1:8010/sdb1 1`
`./hummingbird ring-builder add ./object.builder r1z2-127.0.0.1:6020R127.0.0.1:8020/sdb2 1`
`./hummingbird ring-builder add ./object.builder r1z3-127.0.0.1:6030R127.0.0.1:8030/sdb3 1`
`./hummingbird ring-builder add ./object.builder r1z4-127.0.0.1:6040R127.0.0.1:8040/sdb4 1`
`./hummingbird ring-builder rebalance ./object.builder`
> HUM-38 First pass at ring builder

- common/ring/memcachering.go
- proxyserver/middleware/tempauth.go
The memcache code quits hiding errors so that we can actually get useful
information when things go wrong.
The tempauth code now replies with 503 instead of 401 when talking to
memcache fails.
> HUM-225 Fixed memcache errors and auth relations

- aio/bin/remakerings
- cmd/hummingbird/main.go
- common/ring/builder.go
Also renamed ring-builder to ring in the command line and
cleaned up the doc string a bit.
This is a prerequisite for some of the other commands.
> HUM-204 Adds search command to `hummingbird ring`

- client/directclient.go
- common/ring/memcachering.go
- common/ring/memcachering_test.go
- proxyserver/containerhandlers_test.go
- proxyserver/middleware/authtoken.go
- proxyserver/middleware/authtoken_test.go
- proxyserver/middleware/context.go
- proxyserver/middleware/formpost_test.go
- proxyserver/middleware/ratelimit.go
- proxyserver/middleware/staticweb_test.go
- proxyserver/middleware/tempauth.go
- proxyserver/middleware/tempauth_test.go
- proxyserver/middleware/tempurl_test.go
I made this PR as separate commits to hopefully make it easier to review.
> HUM-111 Refactor memcachering, use not-Swift keys, switch to siphash

- proxyserver/middleware/largeobject.go
I guess that change was supposed to fix some smoke test.  But it broke
a bunch of functional tests.  I think it was trying to output the whole
object when the range header wasn't empty, but didn't have any parseable
ranges.  So I just did that while fixing the functional tests.
> fix xlo range requests

- common/utils.go
- proxyserver/main.go
- proxyserver/middleware/copy.go
- proxyserver/middleware/copy_test.go
- proxyserver/middleware/largeobject.go
- proxyserver/middleware/largeobject_test.go
- proxyserver/middleware/pipe_response.go
- proxyserver/middleware/pipe_response_test.go
- proxyserver/middleware/versioned_writes.go
- proxyserver/middleware/versioned_writes_test.go
> HUM-127 Versioned Writes

- cmd/hummingbird/main.go
- common/ring/builder.go
Also moved set_weight to ringbuilder method
> HUM-198 Adds remove command to hummingbird ring

- cmd/hummingbird/main.go
- tools/main.go
- tools/main_test.go
Direct port of swift's version.
> HUM-199 Add get-nodes.

- client/directclient.go
- common/ring/ring.go
- common/ring/ring_test.go
- common/test/test.go
- objectserver/priorityrep.go
- objectserver/priorityrep_test.go
We almost always want them in order.  Or it doesn't matter.
The one place we want them randomized, we can randomize it.
> HUM-231 get rid of GetNodesInOrder

- cmd/hummingbird/main.go
- common/ring/builder.go
- tools/ring.go
also refactord cli bits of the ring builder to tools
> HUM-207 Add write_ring command to hummingbird ring

- objectserver/updater.go
This should help keep asyncs from piling up and persisting for
long periods of time.
> HUM-232 remove async pendings with quorum success

- client/client.go
- client/directclient.go
- cmd/hummingbird/main.go
- common/srv/server.go
- tools/dispersion.go
- tools/dispersion_test.go
- tools/main.go
populates dispersion and reports metrics on it
> HUM-184 : adding andrewd admin daemon

- common/ring/builder.go
This is a step towards fixing HUM-255.  I also made a first pass
at preallocating space in some of the slices to help with speed
when working with larger partition powers.
> Adds some more randomness to the ring builder

- common/srv/server.go
This closely copies the example found on
https://godoc.org/go.uber.org/zap#example-package--AdvancedConfiguration
> HUM-292 Split logs into error and everything else.

- objectserver/ec/engine.go
- objectserver/main.go
- objectserver/objengine.go
- objectserver/swiftobjeng.go
- objectserver/swiftobjeng_test.go
> HUM-260: stub ec engine

- proxyserver/middleware/authtoken.go
- proxyserver/middleware/authtoken_test.go
Ignore initial stampede, but prevalidate tokens before they actually expire from memcache.
> HUM-298 Prevalidatestampede

- client/directclient.go
Allow the EC scheme be configured in the policy config.
Limit the number of nodes that are written by the proxy using the
object client, which is configured by the policy.
In a world where EC is just another policy, this seems less weird to
me than building the EC scheme into the ring.
> HUM-261: proxy side of EC PUT

- client/directclient.go
- cmd/hummingbird/main.go
- common/conf/policy.go
- objectserver/ec/engine.go
- objectserver/ec/obj.go
Allow basic nursery PUT/GET/DELETE operations.
> HUM-261: nursery PUT/GET/DELETE

- ansible/hosts
- ansible/hummingbird.yml
- ansible/roles/account-server/files/systemd/hummingbird-account-replicator.service
- ansible/roles/account-server/files/systemd/hummingbird-account.service
- ansible/roles/account-server/tasks/main.yml
- ansible/roles/account-server/templates/etc/account-server.j2
- ansible/roles/common/files/etc/hummingbird.conf
- ansible/roles/common/tasks/main.yml
- ansible/roles/container-server/files/systemd/hummingbird-container-replicator.service
- ansible/roles/container-server/files/systemd/hummingbird-container.service
- ansible/roles/container-server/tasks/main.yml
- ansible/roles/container-server/templates/etc/container-server.j2
- ansible/roles/metadata/tasks/main.yml
- ansible/roles/object-server/files/systemd/hummingbird-andrewd.service
- ansible/roles/object-server/files/systemd/hummingbird-object-auditor.service
- ansible/roles/object-server/files/systemd/hummingbird-object-replicator.service
- ansible/roles/object-server/files/systemd/hummingbird-object.service
- ansible/roles/object-server/tasks/main.yml
- ansible/roles/object-server/templates/etc/object-server.j2
- ansible/roles/proxy-server/files/systemd/hummingbird-proxy.service
- ansible/roles/proxy-server/tasks/main.yml
- ansible/roles/proxy-server/templates/etc/proxy-server.j2
- ansible/roles/ring/tasks/main.yml
- ansible/roles/storage/tasks/main.yml
- ansible/storage.yml
I think this is ready for a first pass.
> HUM-317 Adding ansible playbooks for deployment

- objectserver/repconn.go
- objectserver/replicator.go
- objectserver/replicator_test.go
- objectserver/repsrv.go
the replicator has disk-limits to limit the replicator daemon from overloading
devices. priority replication has its own facilities to do this and should not
be affected by the normal limits- otherwise a slow device might constantly be
refusing priority rep calls because of normal replication
> HUM-370 : have priority replication skip disk limits

- objectserver/ec/engine.go
- objectserver/ec/indexdb.go
- objectserver/ec/metadata.go
- objectserver/ec/obj.go
- objectserver/ec/utils.go
- objectserver/main.go
- objectserver/nurseryobjeng.go
- objectserver/nurserystabilizer.go
- objectserver/objengine.go
- objectserver/replicator.go
- objectserver/repsrv.go
Really just PUT, GET, DELETE, and enough of the replicator for
nursery items to be ECed out.
> HUM-262 basic EC functionality

- client/directclient.go
Add a parameter to firstResponse that can limit the number of nodes
it looks at from GetNodes.  This is in support of EC nursery
replica counts.
> HUM-392: add a node limit to firstResponse

- tools/dispersion.go
- tools/dispersion_test.go
- tools/main.go
Also threw in a canceling of the population pass on any error.
> HUM-401 Dispersion population concurrency fix

- docs/replication-tools.md
- objectserver/priorityrep.go
- objectserver/priorityrep_test.go
also retry moveparts just like restoredevice
> HUM-418 : drain 0 weight devs, skip removed drives

- tools/dispersion.go
- tools/drivewatch.go
run container dispersion too. before you run this you'll
have to run:
`
rm /var/local/hummingbird/andrewd.db
`
(best upgrade path eva :p )
> HUM-471 : scan container dispersion

- docs/README.md
- docs/arch.md
I know this is pretty basic, but it's a start and hopefully "good enough
for now".
> HUM-473 Architecture Documentation

- common/utils.go
- tools/dispersion.go
- tools/drivewatch.go
- tools/drivewatch_test.go
Will query the dispersion report and if it finds any partitions
that have been missing for > 3 day (default) it will make
priority replication calls to fix it.
> HUM-440 : heal long missing dispersion partitions

- objectserver/indexdb/ecengine.go
- objectserver/indexdb/ecobj.go
- objectserver/indexdb/indexdb.go
- objectserver/nurseryobjeng.go
- objectserver/nurserystabilizer.go
- objectserver/objengine.go
- objectserver/priorityrep.go
call remote server and get list of partition so you only
run replicate on objects that are missing
> HUM-579 : improve getObjectsToReplicate

- objectserver/indexdb/ecobj.go
- objectserver/indexdb/utils.go
- objectserver/priorityrep.go
- objectserver/priorityrep_test.go
- objectserver/replicator.go
If we get a priority rep request and if we are handoff,
just replicate the shard and delete local shard.
Otherwise we reconstruct the shard and send it over.
Also make sure that Policy is used for restoredevice & moveparts.
> HUM-562 Add replicate/reconstruction for EC object

- objectserver/indexdb/ecobj.go
- objectserver/indexdb/ecobj_test.go
- objectserver/main.go
This will make sense if we ever have multiple algorithms.
It will require any existing data to be deleted.
> HUM-620 add algorithm to scheme in metadata

- tools/db.go
- tools/dispersionpopulateobjects.go
- tools/dispersionscanobjects.go
- tools/progress.go
It was getting a bit hard to read.
Maybe this is better.
It also keeps the last run's last progress output, since, if everything is working optimally, the next pass will start right after the last pass finished and you'd lose what the heck it did.
> HUM-626 Update Andrewd Progress Report

- common/expects.go
- objectserver/indexdb/ecobj.go
May be we can refactor it better later.
> HUM-633 Fix goroutine leak in EC stabilizer.

- cmd/hummingbird/init.go
- objectserver/indexdb/ecengine.go
- objectserver/indexdb/ecengine_test.go
- objectserver/indexdb/ecobj.go
- objectserver/indexdb/ecobj_test.go
Consistently use "shards" to refer to frags.
> HUM-643 s/frags/shards/

- objectserver/indexdb/ecobj.go
- tools/replication.go
No need to reconstruct nothing.
Also, I upped the jobs per device for replication to 5.
> HUM-453 Short circuit 0-byte EC GETs

- objectserver/indexdb/ecengine.go
- objectserver/main.go
- tools/dispersionpopulateobjects.go
Also: HUM-646 Have Andrewd use canonical timestamp format
and I'm setting the timestamp in an extra header for lab debugging
> HUM-650 Double check bytes written == content-length

- objectserver/nurserystabilizer.go
- objectserver/objengine.go
- objectserver/priorityrep.go
- objectserver/replicator.go
- objectserver/replicator_test.go
- objectserver/repsrv.go
- objectserver/swiftobjeng.go
- tools/drivewatch_test.go
now both 3repl and EC priority replication will wait for the
replication to complete during the request. spaces will be fed
back to caller to keep the connection alive
> HUM-585 refactor priority rep

- functional/bulkdelete_test.go
I know nobody runs these, but I hope we get time to make this into an
actual thing someday.
> HUM-682 Update functional tests

- accountserver/server.go
- containerserver/server.go
- proxyserver/accounthandlers.go
- proxyserver/containerhandlers.go
Tempest wants limit 0 to return nothing.
Added x-remove-(account|container)-meta- handling.
> HUM-686 Misc container/account fixes

- proxyserver/middleware/copy.go
(cherry picked from commit 8768b8c9cad2fd35e85501eb77aee44f2bfa31f2)
> HUM-691 Copy fixes for tempest

- common/constraints.go
- common/constraints_test.go
- proxyserver/objhandlers.go
Fix handling x-delete-* headers on object post.
> HUM-689 Tempest test for object expiry.

- client/client.go
- client/directclient.go
- proxyserver/containerhandlers.go
- proxyserver/main.go
- proxyserver/middleware/container_quota.go
- proxyserver/middleware/container_quota_test.go
- tools/dispersion_test.go
Added container quota middleware.
Also had to add SetContainerInfo and update the cache on container head/get.
> Hum685 container quota

- common/ring/builder.go
- tools/db.go
- tools/ring.go
- tools/ringmonitor.go
- tools/unmountedmonitor.go
HUM-657 is tacked on here because otherwise I'd have to remember to update the HUM-671 code later.
> HUM-671 Andrewd auto-rebalance rings

- proxyserver/middleware/keystoneauth.go
One tempest test with mismatching tenant couldn't get a listing.
Another tempest test wasn't getting ctx.StorageOwner when it should have.
> HUM-692 Fix a couple ACL related public object tempest tests

- proxyserver/middleware/formpost.go
Small updates to fix some tempest tests.
> HUM-690: formpost tempest fixes

- proxyserver/middleware/largeobject.go
Fixed test_upload_manifest by adding quotes around the ETag.
Couldn't completely fix test_delete_large_object because they expect
Transfer-Encoding: chunked on a 204 response, which golang's http
won't do.
Also fixed HUM-745 SLO delete to remove the segments.
> HUM-683 Tempest SLO tests

- containerserver/update.go
- objectserver/update.go
we may need to up the vrs number after this truly mindblowing patch
> HUM-768: change some var names

- proxyserver/main.go
- proxyserver/middleware/context.go
- proxyserver/middleware/largeobject.go
- proxyserver/middleware/s3api.go
currently skips auth and only implements list buckets
See `proxyserver/middleware/s3api.go` for config info and example
> HUM-698 Initial S3 compatible POC

- client/directclient.go
- proxyserver/objhandlers.go
distinguish between container 404s and 500s
cache nil in in-memory cache for 404s
cache results in in-memory cache before memcache.Set
log an error when fail to get ProxyCache
lower Memcache.Set timeout to 10s from 30
> HUM-808 : refactor GetContainerInfo some

- client/tracingclient.go
- common/conf/conf.go
- proxyserver/middleware/authtoken.go
and some small bug fixes/cleanup.
> HUM-829 Add tracing to proxy's keystone client

- proxyserver/middleware/authtoken.go
- proxyserver/middleware/s3api.go
- proxyserver/middleware/s3auth.go
- proxyserver/middleware/tempauth.go
Note: probably best to merge this after HUM-750
> Hum 852 Support generic S3 responses

- proxyserver/middleware/s3api.go
- proxyserver/middleware/s3auth.go
also HUM-762 - Adds S3 container HEAD support
> HUM-754 Adds S3 container GET support

- proxyserver/middleware/s3api.go
requires HUM-754 to be merged before this one
> HUM-758 Add S3 object PUT support

- docs/dev/clisdk.md
- docs/dev/index.rst
See also https://github.com/rcbops/rpc-hummingbird/pull/22
> HUM-899 Document CLIs and SDKs

- docs/admin/index.rst
- docs/admin/tuning.md
See also https://github.com/rcbops/rpc-hummingbird/pull/21
> HUM-743 Document Tuning Parameters

- client/proxyclient.go
- proxyserver/accounthandlers.go
also some renaming of client vars  to make things a little clearer
> HUM-906 : dont auto create deleted accounts

- cmd/hummingbird/main.go
- tools/progress.go
- tools/reconcli.go
- tools/reconcli_test.go
Added the Device Status Report back.
All the reports support policies where appropriate.
Updated the list of end points each report uses.
> HUM-744 Update recon policy support, etc.

- objectserver/ecobj.go
Request EC shards concurrently, and serve GET requests as soon as
enough shards have responded to reconstruct the object.
> HUM-642 ec get performance

- common/ring/builder.go
If you have zones <= # replicas and an unequal number of devices in
those zones, the ring wouldn't optimally disperse the partitions.
> HUM-998 Improve ring dispersion for an edge case
